### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dora-gt** [coilhq/interledger-relay#2]
What is the license of this project?

I want to use some of this project to fix https://github.com/emschwartz/interledger-rs/issues/37, so if possible, I want you to clarify the license.

**Comment by sentientwaffle** [comment]
@dora-gt Apache 2.0

**Comment by dora-gt** [comment]
@sentientwaffle thank you!

I copied limit_stream for this PR https://github.com/emschwartz/interledger-rs/pull/61 because combinators module was not public. If you have any better way to do this, please tell me.
(Also referring interledger-relay from interledger-http looks a bit weird)

**Comment by sentientwaffle** [comment]
I agree that copying that module is the simplest solution.
